jobs:
  include:
  - language: python
    python:
      - 3.7.9
      # - 3.8
      # - 3.9
    before_install:
      - python --version
      - pip install -U pip
      - pip install -U pytest
      - pip install pytest-cov
      - pip install pytest-mock
      - pip install codecov
    install:
      - pip install ".[all]"
    script: pytest --cov=metrics_layer/ --cov-report=xml
    after_success:
      - codecov
