[tool.poetry]
name = "granite"
version = "0.1.0"
description = "The open source metrics layer."
authors = ["Paul Blankley <paul@zenlytic.com>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.7"
PyYAML = "^5.4.1"
lkml = "^1.1.0"
requests = "^2.26.0"
GitPython = "^3.1.20"
sqlparse = "^0.4.1"
PyPika = "^0.48.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.8b0"
flake8 = "^3.9.2"
pre-commit = "^2.15.0"
isort = "^5.9.3"
pytest-cov = "^2.12.1"

[tool.black]
line-length = 110

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
