name: Metrics Layer Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
      runs-on: "ubuntu-latest"

      steps:
        - uses: actions/checkout@v3
        
        - name: Set up Python 3.8
          uses: actions/setup-python@v4
          with:
            python-version: 3.8

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry==1.2.1

        - name: Build package
          run: poetry build

        - name: Publish package
          uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
          with:
            user: __token__
            password: ${{ secrets.PYPI_TOKEN }}